### ISSUE TITLE
[BUG]: Enabling experiments makes text formatting in Discord disappear

### ISSUE THREAD

**Issue by themegaxandy** [Friedshrimp-Studio-TW/Discord-Experiments#7] opened 2024-02-07 03:25 UTC
### Describe the bug | BUG描述

When I enable the plugin, even though I don't make any changes to the experiments, Discord's text formatting disappears.

With the plugin activated:
![image](https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/assets/7902295/4f7b7ab1-3c87-4a51-bee4-aa9ccba372f4)

With the plugin deactivated:
![image](https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/assets/7902295/0610f485-51d4-43d5-abd4-8d0687edc1d9)

### Version | 版本

1.4.0

### Code of Conduct | 行為守則

- [X] I have confirmed that what I have BUG Report has not been reported. | 我已確認我所回報的BUG並沒有被回報過

**Comment by VincentX0905** [comment] 2024-02-07 07:25
We did not find this problem after checking.
Please confirm whether you have enabled the Experiments function that caused this problem.

CHECK VIDEO:
https://imgur.com/nRW8847

**Comment by themegaxandy** [comment] 2024-02-07 20:51
There are no experiments activated, and no other plugins activated either. I just enable the plugin, and when I change guilds, the formatting is no longer there.

**Comment by VincentX0905** [comment] 2024-02-08 02:23
what did you mean "change guild" ?
https://imgur.com/Y3U10TB

**Comment by themegaxandy** [comment] 2024-02-08 18:21
By "changing guild" I mean changing servers. But that's exactly what you showed in the video. I don't know what is causing this problem. Reinstalling BetterDiscord does not resolve the issue. And there are no other plugins or experiments activated, so I don't think the problem is being caused by some third party. I just enable the experiments plugin, and the formatting disappears. If only there were other people with this problem, or some way to diagnose it.

**Comment by VincentX0905** [comment] 2024-02-09 03:21
I can't reproduce this issue
This issue has been marked as unknown.
If anyone has the same problem, please reply here

**Remember:**
> This plugin is only maintained and developed for the stable version of Discord(Can be used on PTB or Canary, but versions other than the stable version are not maintained or developed)

**Comment by SteffoSpieler** [comment] 2024-02-15 17:14
I have the same problem. And it's not just formatting. It's also the new notification experiment and more. It seems like the plugin stops never features from working / appearing.

**Comment by themegaxandy** [comment] 2024-03-04 21:06
This bug appears to have been resolved in the latest BetterDiscord update, 1.10.0.

@SteffoSpieler, can you confirm this too?

**Comment by SteffoSpieler** [comment] 2024-03-04 21:41
yeah, seems to work again. At least for now.

**Comment by themegaxandy** [comment] 2024-03-05 19:43
As @SteffoSpieler had noticed, enabling the experiments not only disabled Discord's text formatting, but Discord's newer features. The formatting seems to have worked again in this new BetterDiscord update, as I mentioned previously, but other Discord functions are still disabled when enabling the plugin, such as the possibility of using `@silent` before a message to disable ping of the message.

<img align="left" src="https://github.com/Friedshrimp-Studio-TW/Discord-Experiments/assets/7902295/e2ad8867-403c-4491-9e7c-6198219dedc0">

In the case of this specific function, note that in the first message, the silent message icon was created, and the `@silent` part was removed from the message. 
In the second message, there is no silent message icon, and the `@silent` remained in the message.
The first message was sent with the plugin deactivated, and the second was sent with the plugin activated. Both messages were sent in the same way as in the text box.

As I said, this is just one of the new features that are disabled when enabling the plugin, and there may be others that were not mentioned here.

I don't know if this is a problem with the plugin, with BetterDiscord, or even a way for Discord to 'punish' us for using the experiments.

**Comment by VincentX0905** [comment] 2024-06-04 17:12
We can't confirm if this is a bug on Discord's or Betterdiscord's.
My plugin **only** enables **Discord Experiments**.
Plugins do not impose any restrictions on new or experimental features.

Maybe as @themegaxandy said Discord somehow "punishes" us for using experimental features.
And this function only "punishes" a small part of the population, and it seems to be an experimental content (?

**Comment by leeteral** [comment] 2024-10-03 10:01
This seems to be an issue on Discord's side. This plugin uses native Discord functions to enable experiments and doesn't change anything else such as ability to use formatting or new features.

**Closed as completed** 2024-10-03 11:08 UTC
Labels: BUG | 錯誤, Need Check | 待驗證, Unknow | 未知
